<a href="https://colab.research.google.com/github/Monica-456/Data-Analysis/blob/main/Monica_NumPy_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.create a 1D numpy array containing the values. and displY THE NUMBER oF DIMENSIONS ,SHAPE,SIZE,AND Dtatype
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10 20 30 40 50]
1
(5,)
5
int64


In [ ]:
#2.create a 2d array containing numbers from 1 to 12 arranged in 3 rows and 4 columns and create a 3d array containing numbers 1 to 24 arranged as 2 x3x4
import numpy as np
array1=np.arange(1,13).reshape(3,4)
array2=np.arange(1,25).reshape(2,3,4)
print(array1)
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
#3.create a 1d,2d,3d array conatining only zeros with suitable dimesions
import numpy as np
array_one=np.zeros(5)
array_two=np.zeros((2,3))
array_three=np.zeros((2,4,4))
print(array_one)
print(array_two)
print(array_three)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#4.create a 2x3 array conatining only ones and display its dimensions and shape
import numpy as np
arr=np.ones((2,3))
print(arr)
print(arr.ndim)
print(arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)


In [ ]:
#5.create a 3x4 array where every element is 7 and craeate 4x4 square matrix with 1s on the main daigonal and 0s elesewhere
import numpy as np
arr=np.full((3,4),7)
print(arr)
identical=np.eye(4,4)
print(identical)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#6.Generate:Five random decimal values between 0 and 1,A  2 × 3
#array of random decimal values between 0 and 1.
import numpy as np
arr=np.random.random(5)
print(arr)

[0.9073323  0.95213591 0.42976768 0.17921973 0.92226187]


In [ ]:
#6.b
import numpy as np
arr=np.random.random((2,3))
print(arr)

[[0.45625401 0.18630779 0.41306893]
 [0.75169769 0.22457529 0.03571706]]


In [1]:
#7.Generate a 3 x 3 array of random values between 10 and 50
import numpy as np
arr=np.random.randint(10,51,(3,3))
print(arr)

[[25 32 37]
 [28 49 19]
 [17 45 45]]


In [ ]:
#8.Generate a 2 x 4 array of random values following a standard normal distribution
import numpy as np
arr=np.random.randn(2,4)
print(arr)

[[-0.33369045 -0.35205394 -0.0505474  -0.84870618]
 [-1.45439507 -0.3555515  -1.09157108 -0.12988842]]


In [ ]:
#9.Randomly select 3 colors
import numpy as np
colors=["Red","blue","Green","Yellow","Black"]
result=np.random.choice((colors),3)
print(result)

['Black' 'Green' 'Red']


In [ ]:
#10.Generate five random numbers, set a fixed starting point for the random generator, and generate them again. Verify that both sets are identical.
import numpy as np
arr1=np.random.random(5)
arr2=np.random.random(1)
print(arr2)
result=np.eye()
print(result)

[0.5797214]


TypeError: eye() missing 1 required positional argument: 'N'

In [ ]:
arr2=np.random.random(1)
print(arr2)
result=np.eye((arr1,arr2))
print(result)

In [ ]:
#11.Create an array containing all numbers from 5 to 50 with a step of 5
import numpy as np
arr=np.linspace(5,51,5)
print(arr)

[ 5.  16.5 28.  39.5 51. ]


In [ ]:
#12.Create one version where the original array's order is changed randomly,
# and another version where a randomly reordered copy is produced while keeping the original unchanged.
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.random.shuffle(arr))
version=np.random.permutation(arr)
print(version)

None
[30 50 60 10 40 20]


In [ ]:
#13. Generate 6 equally spaced values between 0 and 100, including both endpoints
import numpy as np
arr=np.linspace(0,100,6)
print(arr)

[  0.  20.  40.  60.  80. 100.]


In [ ]:
#14.Arrange the array into a 3 x 4 matrix, then convert the matrix back into a single 1D array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(arr)
converted=np.ravel(arr)
print(converted)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#15.Change rows into columns and columns into rows. Also create a 3-dimensional NumPy array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
transpose=arr.T
print(transpose)
array_3d=np.arange(1,33).reshape(2,4,4)
print(array_3d)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [ ]:
#16.Convert the data type to float
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.dtype)
print(arr.astype(float))

[10 20 30 40 50]
int64
[10. 20. 30. 40. 50.]


In [ ]:
#17.Retrieve 50, retrieve the last row, retrieve the first two columns, and change 80 to 800.
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[(1,1)])
print(arr[2:3])
print(arr[0:2])
print(arr[(2,1)])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[[70 80 90]]
[[10 20 30]
 [40 50 60]]
80


In [ ]:
#18 Add 25 between 20 and 30, remove 40, and find the total, smallest value, largest value, and average of the resulting array
import numpy as np
arr=np.array([10,20,30,40,50])

print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())

150
10
50
30.0


In [ ]:
#19.Find the variance, standard deviation, 25th percentile, 75th percentile, position of the highest mark, position of the lowest mark, and calculate the base-10 logarithm of each value.
import numpy as np
marks=np.array([24,56,67,72,81,98,95])
print(marks.var())
print(marks.std())
print(np.log10(marks))
print(np.percentile(marks,25))
print(np.percentile(marks,75))


550.5306122448981
23.46338876302607
[1.38021124 1.74818803 1.8260748  1.8573325  1.90848502 1.99122608
 1.97772361]
61.5
88.0


In [2]:
# 20. Combine A and B into one continuous array, arrange A and B one below the other,
# arrange A and B along a newly created dimension, combine all three arrays vertically,
# combine all three arrays horizontally, and divide the combined 1D array into 3 equal parts.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])
print(np.concatenate((A, B)))
print(np.vstack((A, B)))
print(np.stack((A, B)))
print(np.vstack((A, B, C)))
print(np.hstack((A, B, C)))
arr = np.concatenate((A, B, C))
print(np.split(arr, 3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
