<a href="https://colab.research.google.com/github/Monica-456/Data-Analysis/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.create a 1d array containing marks of 20 students using arange()
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2.display its dtype,ndim,shape
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

1
int64
(20,)


In [ ]:
#3.reshape it into a 4x5 array

arr_2d=arr.reshape(4,5)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#4.display the transpose of the array
arr_transpose=arr_2d.T
print(arr_transpose)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [ ]:
#5.convert the transposed array back to 1D using ravel()
a=arr_transpose.ravel()
print(a)

[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]


In [ ]:
#6.create a 1d array of 5 zeros
zeros_a=np.zeros(5)
print(zeros_a)

[0. 0. 0. 0. 0.]


In [ ]:
#PRACTICE 2 AGGREGATIONS
#1.find the sum of all the elements using sum() for given array
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [ ]:
#2. find max and min of values for given array
import numpy as np
marks =np.array([45,78,92,56,88,67,34])
print(np.max(marks))
print(np.min(marks))

92
34


In [ ]:
#3.calculate the average sales using mean() for given sales
import numpy as np
sales=np.array([12000,15000,18000,11000,20000])
print(np.mean(sales))

15200.0


In [ ]:
#4.calculate variance of given data
import numpy as np
data=np.array([10,20,30,40,50])
print(np.var(data))

200.0


In [ ]:
#5.calculate standard deviation of given marks
import numpy as np
marks =np.array([60,70,80,90,100])
print(np.std(marks))

14.142135623730951


In [ ]:
#6.find the 50 percentile of given marks array
import numpy as np
marks=np.array([35,42,60,68,72,80,85,95,100])
print(np.percentile(arr,50))

30.0


In [ ]:
#7.find the 25th and 75th for given marks
import numpy as np
salary=np.array([25000,30000,35000,40000,45000,50000])
print(np.percentile(salary,25))
print(np.percentile(salary,75))

31250.0
43750.0


In [ ]:
#8.find the index of the highest sales value using argmax() of given sales
import numpy as np
sales=np.array([15000,22000,18000,35000,27000,12000])
print(np.argmax(sales))

3


In [ ]:
#9.find the lowest temperature using argmin() temperatures
import numpy as np
temperatures =np.array([32,28,35,25,30,22,38])
print(np.argmin(temperatures))

5


In [ ]:
#10.calculate base 10 logarithm of every element of the array
import numpy as np
arr=np.array([1,10,100,1000,10000])
print(np.log10(arr))

[0. 1. 2. 3. 4.]


In [ ]:
#11.calculate base 2 of the elements
import numpy as np
arr=np.array([1,2,4,8,16,32])
print(np.log2(arr))

[0. 1. 2. 3. 4. 5.]


In [ ]:
#12.calculate the natural logarithm of given array
import numpy as moni
arr=moni.array([1,2,3,4,5])
print(moni.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
#13. calculate the sqyare root of the given array
import numpy as np
arr=np.array([4,9,16,25,36,49,64,81,100])
print(np.sqrt(arr))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
#14.round the nearest interger value
import numpy as np
prices=np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(prices))

[12. 24. 46. 56. 79.]


In [ ]:
#15.find the floor value of every element
import numpy as np
arr=np.array([10.2,15.8,20.4,25.9,30.1])
print(np.floor(arr))

[10. 15. 20. 25. 30.]


In [ ]:
#16.find the ceiling value of every element
import numpy as np
arr=np.array([10.2,15.8,20.4,25.9,30.1])
print(np.ceil(arr))

[11. 16. 21. 26. 31.]


In [ ]:
#17.find the absolute value of every element
import numpy as np
profit=np.array([-5000,3000,-2500,4500,-1000])
print(np.abs(profit))

[5000 3000 2500 4500 1000]


In [ ]:
#18.sort the interger arraybin asending order using np.sort()
import numpy as np
arr=np.array([45,12,89,34,57,23])
print(np.sort(arr))

[12 23 34 45 57 89]


In [ ]:
#19.find the desending order
import numpy as np
arr=np.array([45,12,89,34,57,23])
print(np.sort(arr)[::-1])

[89 57 45 34 23 12]


In [ ]:
#20.

In [ ]:
#day 6 practice concatenation and stacking
#1D Concatenation:
#1.create 2 numpys and concate them into single 1d array
import numpy as np
a=np.array([10,20,30])
b=np.array([40,50,60])
result=np.concatenate((a,b))
print(result)

[10 20 30 40 50 60]


In [ ]:
#2.1D Concatenation-three arrays
#create a 1d arrays containing student marks for three sujects,concatenate all the three arrays into single array
import numpy as np
maths=np.array([98,97,96])
physics=np.array([87,86,85])
chemistry=np.array([76,78,79])
results=np.concatenate((maths,physics,chemistry))
print(results)

[98 97 96 87 86 85 76 78 79]


In [ ]:
#2D Horizontal
#3.given two arrays contain student_id and marks concatenate them horizontally using axis 1
import numpy as np
student_id=np.array([[101,102,103,104,105]]).T
marks=np.array([[98,87,78,89,76]]).T
result=np.concatenate((student_id,marks), axis=1)
print(result)

[[101  98]
 [102  87]
 [103  78]
 [104  89]
 [105  76]]


In [ ]:
#2D Vertical concatenation
#given two 2d arrays containing student records from two classes,concatenate them vertically using axis 0
import numpy as np
classA=np.array([101,102,103,104,105])
classB=np.array([106,107,108,109,110])
result=np.concatenate((classA,classB),axis=0)
print(result)


[101 102 103 104 105 106 107 108 109 110]


In [ ]:
#Horizontal concatenation-employee data
#create one array containing  employee names and another containig their salaries.combine them horizontally to create a single employee
#dataset
import numpy as np
names=np.array([["Satya Monica","Harika","Priya","Darshini","harsh"]]).T
salaries=np.array([[50000,60000,70000,80000,90000]]).T
result=np.concatenate((names,salaries),axis=1)
print(result)

[['Satya Monica' '50000']
 ['Harika' '60000']
 ['Priya' '70000']
 ['Darshini' '80000']
 ['harsh' '90000']]


In [ ]:
#Vertical Concatenation -sales Data    doubt
#create two arrays representing sales records for january and feburary.
#combine both vertically into one dataset
import numpy as np
january=([1000,2000,3000,4000,5000])
february=([2000,4000,6000,8000,9000])
total_sales=np.concatenate((january,february))
print(total_sales)
print(total_sales.ndim)

[1000 2000 3000 4000 5000 2000 4000 6000 8000 9000]
1


In [ ]:
#7. vertical stack practice
#create 3 1d arrays representing sales for three diff regions use np.vstack()
#to stack them into a 2d arrayb
mumbai=np.array([10,20,30])
chennai=np.array([40,50,60])
pune=np.array([70,80,90])
result=np.vstack((mumbai,chennai,pune))
print(result)
print(result.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2


In [ ]:
#8.hstack()
#create 2 arrays and combine them hrizontally
import numpy as np
employee_id=np.array([101,102,103,104])
salary=np.array([45000,55000,65000,75000])
result=np.hstack((employee_id,salary))
print(result)

[  101   102   103   104 45000 55000 65000 75000]


In [ ]:
#stacking more than two arrays
#create three 2d arrays representing productions from those from yhree stores.stack all three arrays verticslly using vstack()
#and display the resulting array
import numpy as np
store_1=np.array([[1,2],[3,4]])
store_2=np.array([[5,6],[7,8]])
store_3=np.array([[9,10],[11,12]])
stacked_stores=np.vstack((store_1,store_2,store_3))
print(stacked_stores)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
