<a href="https://colab.research.google.com/github/Monica-456/Data-Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#day 1
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#creating a numpy single dimension array
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [ ]:
#how to check the dimension of the array - ndim
print(numbers.ndim)

1


In [ ]:
#creating a numpy 2D array - lists in list
numbers = np.array([[10,20,30],[40,50,60]])
print(numbers)

[[10 20 30]
 [40 50 60]]


In [ ]:
#dimension of 2D
print(numbers.ndim)

2


In [ ]:
#creating a 3D array
numbers = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(numbers)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#shape tells us how many elements exists along each dimension(rowa, columns ,height)
numbers.shape

(2, 2, 3)

In [ ]:
#np.arange() used to generate numbers. this is only applicable for 1D array. (n=n-1---10=>9,20=>19)
numbers = np.arange(1,10)
print(numbers)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#start-stop-step - used for genrating numbers in array (odd numbers, 2 helps to skip second nunber)
numbers = np.arange(1,10,2)
print(numbers)

[1 3 5 7 9]


In [ ]:
#(even)
numbers = np.arange(0,10,2)
print(numbers)

[0 2 4 6 8]


In [ ]:
#array of Zeros
#1D
zeros=np.zeros(5)
print(zeros)

#2D
zeros_2d=np.zeros((2,3))
print(zeros_2d)

#3d
zeros_3d=np.zeros((2,2,3))
print(zeros_3d)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#array of ones
#1D
ones_1d=np.ones(5)
print(ones_1d)

#2D
ones_2d=np.ones((2,3))
print(ones_2d)

#3D
ones_3d=np.ones((2,2,3))
print(ones_3d)




[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#np.full=5=count(how many times) 10=number to be displayed [it tells you want 10 to be display 5 times]
#1D
full_id=np.full(5,10)
print(full_id)

#2D
full_id=np.full((5,10),7)
print(full_id)

#3D
full_id=np.full((3,5,10),20)
print(full_id)

[10 10 10 10 10]
[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]
[[[20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]]

 [[20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]]

 [[20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]
  [20 20 20 20 20 20 20 20 20 20]]]


In [ ]:
#reshape= helps to reshape 1D to 2D and 2D to 3D. must and should the elements should match the rows and column.they should fit in them otherwise throws a value error
#product of the 2d should be equal to elements
arr=np.arange(1,7)
print(arr)
a=arr.reshape((2,3)) #2D
print(a)
b=arr.reshape((3,2))
print(b)
c=arr.reshape((1,6))
print(c)
d=arr.reshape((6,1))
print(d)
f=arr.reshape((2,3,1)) #3D
print(f)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
#QUESTIONS ON NUMPY DAY 1
#CREATE  ANUMPY ARRAY CONTATINING NUMBERS 10TO 50 WITH THE STEP OF 5.DISPLAY THE ARRAY
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [ ]:
#create a numpy array containg all even numbers from 2 to 30 using arange()
arr=np.arange(2,31,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
#a company has employee IDs from 1001 to 1020.create a numpy array containing these IDs using arange()
emp_id=np.arange(1001,1021)
print(emp_id)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]


In [ ]:
#create an array containing numvers from 50 down to in descending order using arange()
import numpy as np
numbers=np.arange(50,0,-1)
print(numbers)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [ ]:
#a teacher has the following studets rool numbers
roll_numbers= np.array([101,102,103,104,105,106,107,108])
print(roll_numbers.ndim)
#2D
a=roll_numbers.reshape((1,8))
print(a)
b=roll_numbers.reshape((2,4))
print(b)
c=roll_numbers.reshape((4,2))
print(c)
d=roll_numbers.reshape((8,1))
print(d)
#3D= (412)(421)(118)(181)(811)
e=roll_numbers.reshape((1,2,4))
print(e)
roll_numbers.reshape((1,4,2))
print(f)
g=roll_numbers.reshape((2,1,4))
print(g)
h=roll_numbers.reshape((2,4,1))
print(h)

1
[[101 102 103 104 105 106 107 108]]
[[101 102 103 104]
 [105 106 107 108]]
[[101 102]
 [103 104]
 [105 106]
 [107 108]]
[[101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]]
[[[101 102 103 104]
  [105 106 107 108]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[101 102 103 104]]

 [[105 106 107 108]]]
[[[101]
  [102]
  [103]
  [104]]

 [[105]
  [106]
  [107]
  [108]]]


In [ ]:
 #create an array with element 7 as 10 times in 1D,2D,3D
 #1D
 number=np.full(10,7)
 print(number)
 #2D=(1,10)(10,1)
 number_a=np.full((2,5),7)
 print(number_a)
 number_b=np.full((5,2),7)
 print(number_b)
 #3D=(1,1,10)(1,2,5)(1,5,2)(1,10,1)(2,1,5)(2,5,1)


[7 7 7 7 7 7 7 7 7 7]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
#create a 2d array with xeros
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#create a 2d array with ones
ones=np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#creating 3D with zeros
zeros=np.ones(())

In [ ]:
#cretaing 3D with ones

In [ ]:
#creating a numpy array by defineing datatypes
import numpy as np
arr = np.array([10.9,20.9,3.0,1],dtype="int")
print(arr)
arr1 = np.array([10.9,20.9,3.0,1],dtype="float")
print(arr1)
arr2 = np.array([10.9,20.9,3.0,1],dtype="str")
print(arr2)
print(arr.dtype)

[10 20  3  1]
[10.9 20.9  3.   1. ]
['10.9' '20.9' '3.0' '1']
int64


In [ ]:
#creating an array with string datatype
import numpy as np
names=np.array(["Monica","Satya","Harika","Priya","Darshini"],dtype="str")
print(names)
print(names.dtype)


['Monica' 'Satya' 'Harika' 'Priya' 'Darshini']
<U8


In [ ]:
#day 3
#Linear space


In [ ]:
#array shape
import numpy as np
arr=np.array([10,20,30,40])
print(arr.shape)

(4,)


In [ ]:
#reshape():- helps to reshape an exisiting array.


In [ ]:
#ravel():- helps to compress an 2d or 3d array into 1d array.
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6]])
result=arr.ravel()
print(arr)
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr=np.arange(1,11).reshape(2,5,1)
print(arr)
r=arr.ravel()
print(r)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Transpose the array:- can be performed only on 2d and 3d except.where rows and columns are present
#rows->columns
#columns->rows
#keyword->.T or .transpose
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
result= arr.transpose()
print(result)

[[10 40]
 [20 50]
 [30 60]]


In [ ]:
#Data type conversion
#dtype:- what type is it
#astype:- used to cinvert one type to another

arr=np.array([10,20,30])
new=arr.astype(float)
print(new)
print(new.dtype)

[10. 20. 30.]
float64


In [ ]:
#indexing 1d
#inexing means accessing a specific element from an array
#Numpy uses zero based indexing
#last one is excluded
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0:2])
print(arr[-2:])
print(arr[-3:-1])

[10 20]
[40 50]
[30 40]


In [ ]:
#2d
import numpy as np
arr=np.arange(1,11).reshape(2,5)
print(arr)
print(arr[1,4]) #1st row 4th element
print(arr[0:1]) #slicing start included stop excluded
print(arr[0:2,0:4])
arr[5]=100  #modifications
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
[[1 2 3 4 5]]
[[1 2 3 4]
 [6 7 8 9]]


IndexError: index 5 is out of bounds for axis 0 with size 2

In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr)
arr[5]=100  #modifications
print(arr)
arr[1:4]=90 #helps to moify number of ekements once
print(arr)
n=np.insert(arr,3,98)#insert single element '
print(n)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5 100   7   8   9  10]
[  1  90  90  90   5 100   7   8   9  10]
[  1  90  90  98  90   5 100   7   8   9  10]


In [ ]:
#to insert multiple values at once
n=np.insert(arr,3,[34,4,550])
print(n)

[  1  90  90  34   4 550  90   5 100   7   8   9  10]


In [ ]:
#delection
import numpy as np
arr=np.array([10,20,30,40,50,60])
new=np.delete(arr,4)#5th element gets deleted
print(new)
new=np.delete(arr,[4,5])
print(new)

[10 20 30 40 60]
[10 20 30 40]


In [ ]:
#1st practice questions
#1.using a numpy array containing 10
import numpy as np
arr=np.linspace(0,100,10)
print(arr)


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
#2,
import numpy as np
arr=np.linspace(1,50,15)
print(arr)

[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]


In [ ]:
#3.
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
print(arr[0])#access 1st element
print(arr[-1])#access last element
print(arr[3])#access 4th element
print(arr[5])#access element 60

10
70
40
60


In [ ]:
#4.slicing
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80])
print(arr[0:4])#Extract the first 4 elements
print(arr[2:6])#Extract the elements from index 2 to 5
print(arr[-3:])#Extract the last 3 elements
print(arr[0:7:2])#extract every alternate element
#or
for i in range(0,len(arr)-1,2):
  print(arr[i],end=",")


[10 20 30 40]
[30 40 50 60]
[60 70 80]
[10 30 50 70]
10,30,50,70,

In [ ]:
#5.accessing
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1,1])#access 50
print(arr[0,2])#access 30
print(arr[2,0])#access 70
print(arr[1])#access the whole second row

50
30
70
[40 50 60]


In [ ]:
#day 4 numpy practice notebook

In [ ]:
#day 5
#aggregations 1D
#sum
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.var(arr)) #variance
print(np.std(arr)) #standard deviation
print(np.percentile(arr,100)) #percentile=percentage=0 to 100
print(np.quantile(arr,0.50)) #quantile is always from 0 to 1.
print(np.argmax(arr)) #argmax returns the postion of the highest number unlike max which returns the number
print(np.argmin(arr)) #argmin returns the postion of the least number unlike min which returns the number
print(np.log10(arr))


150
10
50
30.0
200.0
14.142135623730951
50.0
30.0
4
0
[1.         1.30103    1.47712125 1.60205999 1.69897   ]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60]).reshape(2,3)
print(arr)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr,axis=0))  #rows wise sum
print(np.sum(arr,axis=1))  #columns wise sum
print(np.mean(arr))
print(np.std(arr)) #standard deviation
print(np.var(arr)) #variance
print(np.percentile(arr,100))  #percentile =percentage=0 to 100
print(np.quantile(arr,1)) #quantile is always from 0 to 1.
print(np.argmax(arr)) #argmax returns the postion of the highest number unlike max which returns the number
print(np.argmin(arr)) #argmin returns the postion of the least number unlike min which returns the number, in 2d also shows the postion not like rows and columns(x,y)


[[10 20 30]
 [40 50 60]]
210
10
60
[50 70 90]
[ 60 150]
35.0
17.07825127659933
291.6666666666667
60.0
60
5
0
[1 1 1]
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


In [ ]:
#logarithms
import numpy as np
arr=np.array([10,100,1000])
arr1=np.array([10,20,30,40,50,60]).reshape(2,3)
print("log10 of arr :",np.log10(arr))
print("log10 of arr1 :",np.log10(arr1))
print("log2 of arr :",np.log2(arr))
print("log2 of arr1 :",np.log2(arr1))
print("exponentional of arr :",np.log(arr))
print("exponentional of arr1 :",np.log(arr1))

log10 of arr : [1. 2. 3.]
log10 of arr1 : [[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
log2 of arr : [3.32192809 6.64385619 9.96578428]
log2 of arr1 : [[3.32192809 4.32192809 4.9068906 ]
 [5.32192809 5.64385619 5.9068906 ]]
exponentional of arr : [2.30258509 4.60517019 6.90775528]
exponentional of arr1 : [[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]


In [ ]:
#round
import numpy as np
arr=np.array([10.257,20.378,30.304])
print(np.round(arr))  #by default it affects integrs
print(np.round(arr,2)) #only affects the decimals not integers

[10. 20. 30.]
[10.25 20.37 30.3 ]


In [ ]:
#floor:- results to the downward nearest integer value irespective of the deciall value
#ceil:- results the upward nearest integer value
import numpy as np
arr=np.array([10.2,10.8,20.9])
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[10. 11. 21.]
[10. 10. 20.]
[11. 11. 21.]


In [ ]:
#absolute:- makes the  negative numbers into positive even the numbers inside array is either negative it results it in postive
import numpy as np
arr=np.array([-10,-5,0,5,10])
print(np.abs(arr))

[10  5  0  5 10]


In [1]:
#sort:- helps to arrange the elements in asc or desc order,by default its asc if you want desc use ::-1
import numpy as np
arr=np.array([50,10,40,20,30])
print(np.sort(arr))
result=np.sort(arr)[::-1]
print(result)

[10 20 30 40 50]
[50 40 30 20 10]


In [2]:
#TASK
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
#2
marks = np.array([45, 78, 92, 56, 88, 67, 34])
print(np.min(marks), np.max(marks))
#3
sales = np.array([12000, 15000, 18000, 11000, 20000])
print(np.mean(sales))
#4
data = np.array([10, 20, 30, 40, 50])
print(np.var(data))
#5
marks = np.array([60, 70, 80, 90, 100])
print(np.std(marks))
#6
marks = np.array([35, 42, 55, 60, 68, 72, 80, 85, 95, 100])
print(np.percentile(marks, 50))
#7
salary = np.array([25000, 30000, 35000, 40000, 45000, 50000])
print(np.quantile(salary, [0.25, 0.75]))
#8
sales = np.array([15000, 22000, 18000, 35000, 27000, 12000])
print(np.argmax(sales))
#9
temperatures = np.array([32, 28, 35, 25, 30, 22, 38])
print(np.argmin(temperatures))
#10
arr = np.array([1, 10, 100, 1000, 10000])
print(np.log10(arr))
#11
arr = np.array([1, 2, 4, 8, 16, 32])
print(np.log2(arr))
#12
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
#13
arr = np.array([4, 9, 16, 25, 36, 49])
print(np.sqrt(arr))
#14
prices = np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(prices))
#15
arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.floor(arr))
#16
arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.ceil(arr))

150
34 92
15200.0
200.0
14.142135623730951
70.0
[31250. 43750.]
3
5
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4. 5.]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[2. 3. 4. 5. 6. 7.]
[12. 24. 46. 56. 79.]
[10. 15. 20. 25. 30.]
[11. 16. 21. 26. 31.]


In [ ]:
#Day 6-
#joins
#concatenation 1d
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([40,50,60])
result=np.concatenate((arr1,arr2))
print(result)
print(result.ndim) #dimension

[ 1  2  3 40 50 60]
1


In [ ]:
#horizontal 2D concatenation
import numpy as np
arr1=np.array([[1,2,3],
              [3,4,5]])
arr2=np.array([[10,20,30],
              [40,50,60]])
result=np.concatenate((arr1,arr2),axis=1)
print(result)
print(result.ndim)

[[ 1  2  3 10 20 30]
 [ 3  4  5 40 50 60]]
2


In [ ]:
#vertical 2D concatenation
import numpy as np
arr1=np.array([[1,2,3],
              [3,4,5]])
arr2=np.array([[10,20,30],
              [40,50,60]])
result=np.concatenate((arr1,arr2),axis=0)
print(result)
print(result.ndim)

[[ 1  2  3]
 [ 3  4  5]
 [10 20 30]
 [40 50 60]]
2


In [ ]:
#stack vertical
import numpy as np
arr1= np.array([10,20,30])
arr2=np.array([40,50,60])
result=np.stack((arr1,arr2),axis=0)
print(result)
print(result.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
#stack hrizontal
import numpy as np
arr1= np.array([10,20,30])
arr2=np.array([40,50,60])
result=np.stack((arr1,arr2),axis=1)
print(result)
print(result.ndim)

[[10 40]
 [20 50]
 [30 60]]
2


In [ ]:
#converting 1d to 2d using stack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([40,50,60])
result=np.stack((arr1,arr2))
print(result)
print(result.ndim) #dimension

[[ 1  2  3]
 [40 50 60]]
2


In [ ]:
#converting 1d to 2d using stack by specifying axis
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([40,50,60])
result=np.stack((arr1,arr2),axis=1)
print(result)
print(result.ndim) #dimension

[[ 1 40]
 [ 2 50]
 [ 3 60]]
2


In [ ]:
#vertical stack on 1d
import numpy as np
arr1=np.array([10,20,30,])
arr2=np.array([40,50,60])
result=np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
#vertical stack on 2d
import numpy as np
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[10,20,30],
              [40,50,60]])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
2


In [ ]:
#vertical stack on 3d
import numpy as np
arr1=np.arange(1,7).reshape(1,3,2)
arr2=np.arange(8,14).reshape(1,3,2)
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 8  9]
  [10 11]
  [12 13]]]
3


In [ ]:
#horizontal stacking 1d
import numpy as np
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
result=np.hstack((arr1,arr2))
print(result)
print(result.ndim)
result=np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[10 20 30 40 50 60]
1
[[10 20 30]
 [40 50 60]]
2


In [3]:
#2D
arr1 = ([
    [1,2,3],
    [4,5,6]
])
arr2 = ([
    [10,20,30],
    [40,50,60]
])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
2


In [7]:
#Task
#1
import numpy as np
a1 = np.array([10,20,30])
a2 = np.array([40,50,60])
result = np.concatenate((a1,a2))
print(result)
#2
Math = np.array([20,30,40])
Eng = np.array([35,45,55])
Tel = np.array([50,60,70])
result = np.concatenate((Math,Eng,Tel))
print(result)
#3D - 2D arrays Horizontal concate
stu_id = np.array([
    [1,2],
    [3,4]
])
marks = np.array([
    [25,35],
    [45,55]
])
result = np.concatenate((stu_id, marks), axis=1)
print(result)
print(result.ndim)


[10 20 30 40 50 60]
[20 30 40 35 45 55 50 60 70]
[[ 1  2 25 35]
 [ 3  4 45 55]]
2


In [ ]:
#day 7 spliting of arrays
import numpy as np
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,3)
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
#split at specific postions '
import numpy as np
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,[0,3,6])
print(result)

[array([], dtype=int64), array([10, 20, 30]), array([40, 50, 60]), array([], dtype=int64)]


In [ ]:
#split on 2d axis=0
import numpy as np
arr=np.array([[10,20],[30,40],[40,50],[60,70]])
result=np.split(arr,2,axis=0)
print(result)

[array([[10, 20],
       [30, 40]]), array([[40, 50],
       [60, 70]])]


In [ ]:
#split on 2d axis=1
import numpy as np
arr=np.array([[10,20],[30,40],[40,50],[60,70]])
result=np.split(arr,2,axis=1)
print(result)

[array([[10],
       [30],
       [40],
       [60]]), array([[20],
       [40],
       [50],
       [70]])]


In [ ]:
#rasies eroor if the elemets does  not mstch the values
import numpy as np
arr=np.array([[10,20,30],[30,40,50],[40,50,60]])
result=np.split(arr,2,axis=1)
print(result)

ValueError: array split does not result in an equal division

In [ ]:
#rasies eroor if the elemets does  not match the values(COUSTOMIZED INDEX)/
import numpy as np
arr=np.array([[10,20,30],[30,40,50],[40,50,60]])
result=np.split(arr,[1,3],axis=1)
print(result)

[array([[10],
       [30],
       [40]]), array([[20, 30],
       [40, 50],
       [50, 60]]), array([], shape=(3, 0), dtype=int64)]
